/*
 * constants.h
 *
 *  Created on: Nov 22, 2010
 */

#ifndef CONSTANTS_H_
#define CONSTANTS_H_

#define GSCALE_VERSION_MAJOR 1
#define GSCALE_VERSION_MINOR 1

#ifndef GSCALE_OK
#define GSCALE_OK 1
#endif

#ifndef GSCALE_NOK
#define GSCALE_NOK 0
#endif

#ifndef GSCALE_YES
#define GSCALE_YES 1
#endif

#ifndef GSCALE_NO
#define GSCALE_NO 0
#endif

#ifndef GSCALE_NODE_TYPE_LOCAL
#define GSCALE_NODE_TYPE_LOCAL 1
#endif
#ifndef GSCALE_NODE_TYPE_REMOTE
#define GSCALE_NODE_TYPE_REMOTE 0
#endif

#ifndef GSCALE_DESTINATION_TYPE_HOST
#define GSCALE_DESTINATION_TYPE_HOST 1
#endif
#ifndef GSCALE_DESTINATION_TYPE_NODE
#define GSCALE_DESTINATION_TYPE_NODE 2
#endif
#ifndef GSCALE_DESTINATION_TYPE_GROUPNAMESPACE
#define GSCALE_DESTINATION_TYPE_GROUPNAMESPACE 4
#endif
#ifndef GSCALE_DESTINATION_TYPE_GROUP
#define GSCALE_DESTINATION_TYPE_GROUP 8
#endif

#ifndef GSCALE_PACKET_UNASSIGNED
#define GSCALE_PACKET_UNASSIGNED 0
#endif

#endif /* CONSTANTS_H_ */
